[[redirects]]
  from = "/api/*"
  to = "https://scholar-api-prod.naish.io/:splat"
  headers = { X-From = "Netlify" }
  force = true
	status = 200

[[redirects]]
  from = "/docs/*"
  to = "https://scholar-docs.readme.io/:splat"
  force = true
	status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
