name: Deploy to github pages
on:
  push:
    branches:
      - modernisation

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Log git info
        run: |
          git status
          git branch
          git config --list
      - name: Clean install dependencies
        run: npm ci
      - name: Build production assets
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
