name: Deploy
on:
  push:
    branches:
      - modernisation

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  gh-pages-deploy:
    name: Deploying frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: ./app/dist
