name: Deploy
on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

defaults:
  run:
    shell: bash

jobs:
  netlify-deploy:
    name: Deploying frontend
    runs-on: ubuntu-latest
    working-directory: app
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          build_directory: ./app/dist
          install_command: echo "already installed!"
          build_command: cp app/netlify.toml app/dist/
